Cc 25
Sid-Athos/CleanCodeRepo4AL22 pull request #18
Opened 2023-01-21 11:28 UTC by arnaud111

UwU

2023-01-30 10:47 UTC, Sid-Athos requested changes
Il manque des tests sur le level up aussi et le fait de gagner de la moula quand tu gagnes

2023-01-30 10:47 UTC, Sid-Athos commented on cleancode/clean-code-domain/src/main/java/com/cleancode/domain/services/collectioncard/CollectionCardFighterService.java
> +    private Long getDamage(CardCollectionCard cardAttacker, CardCollectionCard cardAttacked) {
La méthode a un nom un peu chelou, on dirait un getter de classe mais on calcule les vrais dégâts.

2023-01-30 10:47 UTC, Sid-Athos commented on cleancode/clean-code-domain/src/test/java/services/CollectionCardFighterServiceTest.java
> +            collectionCardFighterService.fight("invalid-username", "valid-username", "valid-card-reference", "valid-card-reference2");
nom de méthode aussi pas très évocateur

2023-02-08 17:46 UTC, arnaud111 commented
j'avais zappé

2023-02-21 21:51 UTC, Sid-Athos requested changes

2023-02-21 21:51 UTC, Sid-Athos commented on cleancode/clean-code-domain/src/main/java/com/cleancode/domain/pojo/card/CardCollectionCard.java
> +        this.armor = ((Double) (this.armor * 1.1)).longValue();
Enum ou propriété statique, ou DoubleUnaryOperator.

2023-02-21 21:51 UTC, Sid-Athos commented on cleancode/clean-code-domain/src/main/java/com/cleancode/domain/ports/in/collectioncard/CollectionCardFighter.java
> +    CardCollectionCard launchFightBetweenTwoCards(String userNameAttacker, String userNameAttacked, String cardAttackerReference, String cardAttackedReference) throws CleanCodeException;
Créer un objet opponent qui a la propriété userName, fightingCard par ex

2023-02-21 21:51 UTC, Sid-Athos commented on cleancode/clean-code-domain/src/main/java/com/cleancode/domain/services/collectioncard/CollectionCardFighterService.java
> +        BusinessUserClientInfo userAttacker = userAccountPersistencePort.findUserByUserName(userNameAttacker).orElseThrow(() -> new CleanCodeException(CleanCodeExceptionsEnum.DB_COMPONENT_INVALID_USE
Normalement tu as déjà la liste des cartes de l'utilisateur dans sa collection, donc rechercher dedans plutôt que refaire un appel db

2023-02-21 21:51 UTC, Sid-Athos commented on cleancode/clean-code-domain/src/main/java/com/cleancode/domain/services/collectioncard/CollectionCardFighterService.java
> +        IntStream.iterate(0, i -> (i + 1) % 2).limit(Integer.MAX_VALUE)
Mashallah la programmation fonctionnelle. 
g joui

2023-02-21 21:51 UTC, Sid-Athos commented on cleancode/clean-code-domain/src/main/java/com/cleancode/domain/services/collectioncard/CollectionCardFighterService.java
> +                        cardAttacker.removeLifePoints(damage_card_attacked);
pas mashallah le ssssssnake casssssse

2023-02-21 21:51 UTC, Sid-Athos commented on cleancode/clean-code-persistence/src/main/java/com/cleancode/persistence/mappers/collectincard/CardCollectionCardMapper.java
> +            @Mapping(source="cardCollectionCardReference", target="cardCollectionCardReference"),
tu peux enlever c'est le même nom

2023-02-21 21:51 UTC, Sid-Athos commented on cleancode/clean-code-persistence/src/main/java/com/cleancode/persistence/mappers/collectincard/CardCollectionCardMapper.java
> +            @Mapping(source="cardCollectionCardReference", target="cardCollectionCardReference"),
Ca change que quand les noms de propriété changent wink wink

2023-02-22 12:35 UTC, arnaud111 commented on cleancode/clean-code-domain/src/main/java/com/cleancode/domain/services/collectioncard/CollectionCardFighterService.java
> +        IntStream.iterate(0, i -> (i + 1) % 2).limit(Integer.MAX_VALUE)
hihihi

2023-02-23 01:41 UTC, Sid-Athos approved these changes

2023-02-23 01:42 UTC, merged